Feature/feature 2
Takhir30/Fl_ic pull request #5
Opened 2018-02-02 06:46 UTC by Takhir30

2018-02-02 07:22 UTC, strelass commented on alembic/env.py
> +    config.set_main_option('sqlalchemy.url', 'postgresql://' + login + ':' + password + '@' + host + '/' + name)
а откуда берутся эти параметры?

2018-02-05 07:54 UTC, strelass requested changes

2018-02-05 07:54 UTC, strelass commented on alembic/env.py
> +    name = ['name']
эта функция должна быть в твоём файле а сюда только импортиться

2018-02-05 08:21 UTC, strelass commented on alembic/env.py
> +config.set_main_option('sqlalchemy.url',set_adres())
пробел потерял

2018-02-05 11:36 UTC, strelass commented on Data.txt
> +host = postgres
у тебя хост постгрес?

2018-02-05 11:36 UTC, strelass commented on alembic/env.py
> +config.set_main_option('sqlalchemy.url', set_adres('Data.txt'))
typo: address

2018-02-05 11:37 UTC, strelass commented on alembic/env.py
> +from db import set_adres
а где этот файл `db` не вижу его тут

2018-02-05 12:01 UTC, Takhir30 commented on Data.txt
> +host = postgres
исправил

2018-02-05 12:01 UTC, Takhir30 commented on alembic/env.py
> +config.set_main_option('sqlalchemy.url', set_adres('Data.txt'))
исправил

2018-02-05 12:06 UTC, Takhir30 commented on alembic/env.py
> +from db import set_adres
Этот файл в пр-3

2018-02-05 12:25 UTC, strelass commented on alembic/env.py
> +from db import set_adres
и что он там делает? пр - это законченный кусок работы, после вливания которого в рабочую ветку должен получиться рабочий билд, а твой код попросту не запустится

2018-02-05 12:26 UTC, strelass commented
пиши названия коммитов более подробно, чтобы я не гадал что в этот раз "fixed"

2018-02-05 13:27 UTC, strelass requested changes

2018-02-05 13:27 UTC, strelass commented on db.py
> +    return "'postgresql://' + {} + ':' + {} + '@' + {} + '/' + {}".format(login, password, host, dbname)
перед закрытием пра я оставил тут комент

2018-02-05 13:27 UTC, strelass commented on db.py
> +class User(Base):
этот класс не нужен

2018-02-05 13:27 UTC, strelass commented on db.py
> +for instance in session.query(User):
1. откуда берётся сессия?
2. я кажется говорил что мы не будем использовать сессии

2018-02-05 13:27 UTC, strelass commented on db.py
> +if __name__ = '__main__':
зачем тут точка входа и откуда берётся функция main()?

2018-02-05 15:13 UTC, strelass commented on db.py
> +    return "postgresql://{}:{}@{}/{}".format(login, password, host, dbname)
смотри можно писать так
1) `"postgresql://{login}:{password}@{host}/{dbname}".format(login=login, password=password, host=host, dbname=dbname)`
2) `f"postgresql://{login}:{password}@{host}/{dbname}"` - такое работает в питоне 3.6

2018-02-05 15:14 UTC, strelass approved these changes

2018-02-05 15:14 UTC, merged